---
- hosts: heartbeat
  vars:
    home: /home/ubuntu
    go_root_bin: /usr/local/go/bin
    program: bitmarkd-broadcast-monitor
    dir: monitor
    config_file: monitor.conf
    empty_char: /dev/null

  environment:
    GOPATH: "{{ home }}/gocode"
    GO111MODULE: "on"

  tasks:
    - name: create monitor directory
      file: path="~/{{ dir }}" state=directory mode=0755

    - name: copy monitor config file
      template:
        src: "{{ config_file }}"
        dest: "{{ dir }}/{{ config_file }}"

    - name: udpate monitor program
      shell: "/usr/local/go/bin/go get -u github.com/jamieabc/{{ program }}"
      async: 60
      poll: 10

    - name: find running pid
      shell: "ps -ef | grep -v grep | grep -w {{ program }} | awk '{print $2}'"
      register: running_process

    - name: kill process
      shell: "kill {{ item }}"
      with_items: "{{ running_process.stdout_lines }}"

    - wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
        timeout: 31
      with_items: "{{ running_process.stdout_lines }}"
      ignore_errors: yes
      register: force_kill_process

    - name: force kill
      ignore_errors: yes
      shell: "kill -9 {{ item }}"
      with_items: "{{ force_kill_process.results | select('failed') | map(attribute='item') | list }}"

    - name: start to monitor
      shell: "nohup {{ home }}/gocode/bin/{{ program }} -c {{ config_file }} <{{ empty_char }} >{{ empty_char }} 2>&1 &"
      args:
        chdir: "{{ dir }}"
